# docker run --name api-solid-pg -e POSTGRESQL_USERNAME=docker
# -e POSTGRES_PASSWORD=docker -e POSTGRESQL_DATABASE=apisolid 
# -p 5432:5432 bitnami/postgresql:latest 

# comando de criação acima, resumido abaixo para facilitar a criação de container

version: '3'

services: 
  api-solid-pg:
    image: bitnami/postgresql:latest
    ports: 
      - 5432:5432
    environment: 
      - POSTGRESQL_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
